name: wine-feature-pipeline-quarter-daily

on:
  workflow_dispatch:
#  schedule:
#    - cron: "11 4,10,16,22 * * *"

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: setup python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r ./wine/requirements.txt

      - name: Make the shell file executable
        run: chmod +x ./wine/run-wine.sh

      - name: Run quarter daily feature addition and inference
        env: 
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: bash ./wine/run-wine.sh
